# Generated by Django 4.2.6 on 2024-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_carreserve_ticket_code_alter_rentcar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqtomechanic',
            name='detail_head',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
